# Generated by Django 3.2.2 on 2021-06-23 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40)),
                ('passfield', models.CharField(max_length=40)),
                ('classroomname', models.TextField(blank=True, default='no name', max_length=40, null=True)),
                ('equipmentnumber', models.TextField(blank=True, default='no name', max_length=32, null=True)),
                ('CO2conce', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('peoplenumber', models.IntegerField(blank=True, default='-1')),
            ],
        ),
    ]
